# Generated by Django 2.1.15 on 2020-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(blank=True, db_column='reading', null=True)),
                ('timestamp', models.DateTimeField(db_column='timestamp')),
                ('sensortype', models.CharField(db_column='sensortype', max_length=255)),
            ],
            options={
                'db_table': 'Sensor_Readings',
                'managed': False,
            },
        ),
    ]
